name: Release Build

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Clean and install dependencies
        run: |
          rm -f yarn.lock
          rm -f package-lock.json
          rm -rf node_modules
          yarn install

      # Import fix for React Native components
      - name: Fix React Native imports
        run: |
          echo "Updating React Native component imports..."
          if [ -f "babel.config.js" ]; then
            echo "module.exports = {" > babel.config.js
            echo "  presets: ['module:metro-react-native-babel-preset']," >> babel.config.js
            echo "  plugins: ['react-native-reanimated/plugin']" >> babel.config.js
            echo "};" >> babel.config.js
          fi

      # Run Metro bundler clean
      - name: Clean Metro bundler cache
        run: |
          yarn react-native start --reset-cache &
          sleep 10
          pkill -f "react-native start"

      # Setup Java for Android build
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Android SDK and build tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Update Android build files
      - name: Update Android Gradle config
        run: |
          cd android
          if [ -f "build.gradle" ]; then
            sed -i 's/com.android.tools.build:gradle:7.0.4/com.android.tools.build:gradle:7.4.2/g' build.gradle || true
          fi

      # Generate Android Release
      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease

      # Upload build artifacts
      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: android/app/build/outputs/apk/release/

      # Update release with builds and notes
      - name: Update Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            android/app/build/outputs/apk/release/*.apk
          body: |
            ## Release Notes
            This release includes:
            - Bug fixes for React Native component imports
            - Updated Gradle configuration
            - Optimized build process
            
            ### Binary Files
            - Android APK: Available in the assets section below
            
            Please download the appropriate binary for your platform.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
