name: Release Build

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests if they exist (non-blocking)
      - name: Run tests
        continue-on-error: true
        run: |
          if grep -q "\"test\":" package.json; then
            echo "Running tests..."
            yarn test
          else
            echo "No test command found in package.json - skipping tests"
            echo "Consider adding tests for better code quality"
          fi

      # TypeScript check
      - name: Type check
        run: yarn tsc --noEmit

      # Setup Java for Android build
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Android SDK and build tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Generate Android Release
      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # Upload build artifacts
      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: android/app/build/outputs/apk/release/

      # Update release with builds and notes
      - name: Update Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            android/app/build/outputs/apk/release/*.apk
          body: |
            ## Release Notes
            This release includes:
            - New features and improvements
            - Bug fixes and optimizations
            
            ### Binary Files
            - Android APK: Available in the assets section below
            
            Please download the appropriate binary for your platform.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
