name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Build Android bundle
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Build iOS archive
        run: |
          cd ios
          xcodebuild -workspace volunteam.xcworkspace -scheme volunteam archive -configuration Release -archivePath $PWD/build/volunteam.xcarchive

      - name: Upload Android artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: ios/build/volunteam.xcarchive

      - name: Create Release Notes
        run: |
          echo "Build completed successfully!" > release_notes.txt
          echo "Download links:" >> release_notes.txt
          echo "- Android bundle: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> release_notes.txt
          echo "- iOS archive: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> release_notes.txt

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_notes.txt
          body_path: release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
